{{- if .Values.slack.webhookUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ding-k8s-job.fullname" . }}
  labels:
    {{- include "ding-k8s-job.labels" . | nindent 4 }}
type: Opaque
stringData:
  SLACK_WEBHOOK_URL: {{ .Values.slack.webhookUrl | quote }}
{{- end }}
