image:
  repository: alpine
  tag: "3"
command: ["sh", "-c", "echo 'workload'; sleep 1; exit 0"]
existingSecret: ci-test-secret
extraNotifiers:
  webhook-fake:
    type: webhook
    url: ${WEBHOOK_URL}
